apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: merchant
  name: merchant-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: merchant
    spec:
      containers:
      - image: steph/merchant:latest
        name: merchant
        ports:
        - name: merchant
          containerPort: 8081  
---
# ClusterIP Service

apiVersion: v1
kind: Service
metadata:
  name: merchantsvc
  namespace: dev
spec:
  type: ClusterIP       #ClusterIP is the default service type for K8s
  selector:              # seletor must be thesame as the label for the application
    app: merchant 
  ports:
    - port: 8081
      targetPort: 8081