apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: shopping
  name: shopping-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: shopping/v1
    spec:
      containers:
      - image: steph/Shopping:latest
        name: shopping
        ports:
        - name: shopping
          containerPort: 8082  
---
# ClusterIP Service

apiVersion: v1
kind: Service
metadata:
  name: shoppingsvc
  namespace: dev
spec:
  type: ClusterIP       #ClusterIP is the default service type for K8s
  selector:              # seletor must be thesame as the label for the application
    app: shopping 
  ports:
    - port: 8082
      targetPort: 8082