version: '3'

services:
  merchant:
    image: steph/merchant:latest
    container_name: merchant
    restart: always
    user: root
    ports:
      - 8081:8081
    networks:
      - cicdnetwork
  shopping:
    image: steph/shopping:latest
    container_name: shopping
    restart: always
    user: root
    ports:
      - 8082:8082
    networks:
      - cicdnetwork

networks:
  cicdnetwork: